### ISSUE TITLE
Fix [Antecedentes]Error al cargar formulario

### ISSUE THREAD

**Issue by Barbara-Alvarez** [Historia-Clinica-La-Rioja/historia_clinica_LR#231]
## ℹ Versión
2.30.2
## ⚠ Descripción 
	Se detectó un problema: Al intentar guardar un formulario en la sección de antecedentes, el sistema muestra un error del tipo 500 Internal Server Error, originado en el service worker. Este problema impide que los datos ingresados en el formulario se guarden correctamente, afectando la funcionalidad esperada de esta sección. 
##💡 Pasos para reproducir
1.	Ingresamos a https://hsi-dev.nubecenter.com.ar/
2.	Nos logueamos con usuario y contraseña.
3.	Seleccionamos “CAPS FALDEO DEL VELAZCO”.
4.	Seleccionamos “Historia Clínica”.
5.	Buscamos a el paciente colocando su DNI.
6.	Visualizamos la pestaña “Antecedentes”.
7.	Completamos un nuevo formulario.
8.	Visualizamos la sección “Madre”.

## ❌ Resultado actual
 
![image](https://github.com/user-attachments/assets/acde9e1b-9d65-4f77-ac80-08d45141a87b)

 
![image](https://github.com/user-attachments/assets/61e8c3ea-6011-4cf9-b893-a26bb821b406)

## ℹ Información adicional
•	Ingresamos con:
		Usuario: jamartin
		Contraseña: Dgsdygsi24
•	Paciente:
o	Nombre: María Eugenia Carrizo
o	DNI: 29284010

**Comment by RLRama** [comment]
Tras revisar los logs en el entorno de desarrollo, se reveló que:

1. el error salta porque las tablas de la base de datos están presentes pero vacías, lo que viola las restricciones de foreign keys (no se puede registrar un cuestionario que ni existe) de las tablas que almacenan la información de los cuestionarios

se puede asumir también que en cualquier otro entorno que aparezcan es por el problema que estamos teniendo con que se vacían las tablas nuestras en la BDD, acá el log relevante:

```
2024-11-20 12:40:24.598  INFO 1 --- [nio-8080-exec-4] .p.q.g.c.c.CreateQuestionnaireController : Received request to create questionnaire response for patientId: 1 in institutionId: 50
2024-11-20 12:40:24.598  INFO 1 --- [nio-8080-exec-4] n.p.q.g.c.d.s.CreateQuestionnaireService : Starting transaction to create questionnaire response for patientId: 1
2024-11-20 12:40:24.601  WARN 1 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23503
2024-11-20 12:40:24.601 ERROR 1 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "minsal_lr_questionnaire_response" violates foreign key constraint "minsal_lr_questionnaire_response_questionnaire_id_fkey"
 Detail: Key (questionnaire_id)=(2) is not present in table "minsal_lr_questionnaire".
2024-11-20 12:40:24.630 ERROR 1 --- [nio-8080-exec-4] .p.q.g.c.c.CreateQuestionnaireController : Error creating questionnaire response for patientId: 1
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [minsal_lr_questionnaire_response_questionnaire_id_fkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276) ~[spring-orm-5.3.14.jar!/:5.3.14]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.14.jar!/:5.3.14]
at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551) ~[spring-orm-5.3.14.jar!/:5.3.14]
at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.3.14.jar!/:5.3.14]
at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.3.14.jar!/:5.3.14]
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-5.3.14.jar!/:5.3.14]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174) ~[spring-data-jpa-2.6.0.jar!/:2.6.0]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.14.jar!/:5.3.14]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar!/:5.3.14]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.14.jar!/:5.3.14]
at com.sun.proxy.$Proxy547.save(Unknown Source) ~[na:na]
at net.pladema.questionnaires.general.create.domain.service.CreateQuestionnaireService.createQuestionnaireResponse(CreateQuestionnaireService.java:40) ~[hospital-api-2.30.2_MinSaludLR.jar!/:na]
at net.pladema.questionnaires.general.create.domain.service.CreateQuestionnaireService$$FastClassBySpringCGLIB$$af99aade.invoke(<generated>) ~[hospital-api-2.30.2_MinSaludLR.jar!/:na]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.14.jar!/:5.3.14]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.14.jar!/:5.3.14]
```

una vez que se resuelva lo de la base de datos no deberíamos tener más este problema @Barbara-Alvarez 

(comentario replicado de Taiga)
